import type { Product, Category, BlogPost } from './types';

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Classic Denim Jacket',
    description: 'A timeless denim jacket that belongs in every wardrobe. Made from 100% organic cotton.',
    price: 89.99,
    originalPrice: 120.00,
    category: 'jackets',
    brand: 'Urban Threads',
    images: ['product-1-1', 'product-1-2'],
    rating: 4.5,
    reviewCount: 120,
    attributes: {
      'Color': ['Blue', 'Black'],
      'Material': ['Denim'],
    },
    variants: {
      'Size': ['S', 'M', 'L', 'XL'],
    },
    tags: ['new-arrival', 'best-seller'],
    slug: 'classic-denim-jacket-prod_1',
  },
  {
    id: 'prod_2',
    name: 'Organic Cotton T-Shirt',
    description: 'Soft, breathable, and eco-friendly. This basic tee is a must-have.',
    price: 24.99,
    category: 'tops',
    brand: 'EcoWear',
    images: ['product-2-1'],
    rating: 4.8,
    reviewCount: 250,
    attributes: {
      'Color': ['White', 'Black', 'Gray'],
      'Material': ['Cotton'],
    },
    variants: {
      'Size': ['XS', 'S', 'M', 'L', 'XL'],
    },
    slug: 'organic-cotton-t-shirt-prod_2',
  },
  {
    id: 'prod_3',
    name: 'Slim-Fit Chinos',
    description: 'Versatile slim-fit chinos for a sharp, modern look. Perfect for any occasion.',
    price: 65.00,
    category: 'bottoms',
    brand: 'Modern Man',
    images: ['product-3-1'],
    rating: 4.6,
    reviewCount: 95,
    attributes: {
      'Color': ['Khaki', 'Navy', 'Black'],
      'Material': ['Cotton Blend'],
    },
    variants: {
      'Size': ['30', '32', '34', '36'],
    },
    tags: ['best-seller'],
    slug: 'slim-fit-chinos-prod_3',
  },
  {
    id: 'prod_4',
    name: 'Floral Sundress',
    description: 'A light and airy sundress with a beautiful floral print, perfect for warm days.',
    price: 75.50,
    category: 'dresses',
    brand: 'Summer Bloom',
    images: ['product-4-1'],
    rating: 4.7,
    reviewCount: 78,
    attributes: {
      'Color': ['Yellow', 'Blue'],
      'Pattern': ['Floral'],
    },
    variants: {
      'Size': ['S', 'M', 'L'],
    },
    slug: 'floral-sundress-prod_4',
  },
  {
    id: 'prod_5',
    name: 'Leather Ankle Boots',
    description: 'Handcrafted leather boots that combine style and durability.',
    price: 150.00,
    category: 'shoes',
    brand: 'Heritage Co.',
    images: ['product-5-1'],
    rating: 4.9,
    reviewCount: 150,
    attributes: {
      'Color': ['Brown', 'Black'],
      'Material': ['Leather'],
    },
    variants: {
      'Size': ['7', '8', '9', '10', '11'],
    },
    slug: 'leather-ankle-boots-prod_5',
  },
  {
    id: 'prod_6',
    name: 'Cashmere Wool Sweater',
    description: 'Luxuriously soft and warm, this cashmere blend sweater is a winter essential.',
    price: 125.00,
    originalPrice: 180.00,
    category: 'tops',
    brand: 'Luxe Knits',
    images: ['product-6-1'],
    rating: 4.8,
    reviewCount: 60,
    attributes: {
      'Color': ['Heather Gray', 'Charcoal'],
      'Material': ['Cashmere Blend'],
    },
    variants: {
      'Size': ['S', 'M', 'L', 'XL'],
    },
    tags: ['on-sale'],
    slug: 'cashmere-wool-sweater-prod_6',
  },
  {
    id: 'prod_7',
    name: 'Striped Linen Shirt',
    description: 'Stay cool and stylish with this breathable striped linen shirt.',
    price: 59.99,
    category: 'tops',
    brand: 'Coastal Living',
    images: ['product-7-1'],
    rating: 4.4,
    reviewCount: 45,
    attributes: {
      'Color': ['Blue/White Stripe'],
      'Material': ['Linen'],
    },
    variants: {
      'Size': ['M', 'L', 'XL'],
    },
    slug: 'striped-linen-shirt-prod_7',
  },
    {
    id: 'prod_8',
    name: 'Classic Trench Coat',
    description: 'An iconic, weather-resistant trench coat for a sophisticated outerwear option.',
    price: 220.00,
    category: 'jackets',
    brand: 'London Fog',
    images: ['product-8-1'],
    rating: 4.9,
    reviewCount: 88,
    attributes: {
      'Color': ['Beige', 'Black'],
      'Material': ['Cotton Gabardine'],
    },
    variants: {
      'Size': ['S', 'M', 'L'],
    },
    tags: ['best-seller'],
    slug: 'classic-trench-coat-prod_8',
  },
];

export const categories: Category[] = [
    {
        id: 'cat_1',
        name: 'Men',
        image: 'category-men',
        slug: 'men',
    },
    {
        id: 'cat_2',
        name: 'Women',
        image: 'category-women',
        slug: 'women',
    },
    {
        id: 'cat_3',
        name: 'Kids',
        image: 'category-kids',
        slug: 'kids',
    },
];

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    title: "The 5 Denim Trends You Need to Know for this Season",
    slug: "5-denim-trends-for-this-season",
    excerpt: "From baggy jeans to classic jackets, we're breaking down the must-have denim pieces that are taking over the fashion world.",
    category: "Trends",
    date: "July 20, 2024",
    author: "Jane Doe",
    imageId: "product-1-1",
    content: "Denim is a timeless fabric, but its trends evolve with each season. This year, we're seeing a resurgence of 90s and Y2K styles, mixed with modern cuts. First on the list is the baggy jean. Say goodbye to skinny fits and embrace comfort with wide-leg and relaxed silhouettes. They pair perfectly with a fitted top to balance the proportions. Second, the denim midi skirt is making a huge comeback. It's versatile enough for both casual and semi-formal looks. Third, oversized denim jackets continue to be a staple. Look for vintage washes and unique details. Fourth, denim-on-denim, or the 'Canadian tuxedo', is back in a big way. The key is to play with different washes to create contrast. Finally, patchwork denim offers a unique, handcrafted feel that makes a bold statement.",
  },
  {
    id: 2,
    title: "How to Build a Sustainable Wardrobe That Lasts",
    slug: "how-to-build-a-sustainable-wardrobe",
    excerpt: "Eco-friendly fashion is more than a trend. Learn how to invest in quality pieces that are good for your style and the planet.",
    category: "Sustainability",
    date: "July 15, 2024",
    author: "John Smith",
    imageId: "product-6-1",
    content: "Building a sustainable wardrobe starts with a mindset shift: quality over quantity. Instead of chasing fast fashion trends, focus on timeless pieces made from eco-friendly materials like organic cotton, linen, Tencel, and recycled fabrics. A great first step is to audit your current wardrobe. Understand what you own, what you actually wear, and what you need. This prevents impulse buys. When you do shop, research brands that are transparent about their supply chain and ethical practices. Look for certifications like GOTS (Global Organic Textile Standard) or Fair Trade. Lastly, learn basic clothing care and repair. Mending a small tear or replacing a button can significantly extend the life of your garments, reducing waste and saving you money in the long run.",
  },
    {
    id: 3,
    title: "Styling 101: The Art of Layering",
    slug: "styling-101-the-art-of-layering",
    excerpt: "Master the art of layering to create versatile and chic outfits for any season. We'll show you how with key pieces from our collection.",
    category: "Style Guides",
    date: "July 10, 2024",
    author: "Emily White",
    imageId: "product-8-1",
    content: "Layering is a practical and stylish way to add depth, texture, and interest to your outfits. The fundamental rule is to layer from thin to thick. Start with a lightweight base layer, like a simple tee or a silk camisole. Add a mid-layer, such as a cardigan, a button-down shirt (worn open), or a fine-knit sweater. Your final layer should be your outerwear, like a trench coat, a blazer, or a leather jacket. Pay attention to proportions and lengths. A long coat over a shorter dress can create a beautiful silhouette. Don't be afraid to mix textures—combine denim with cashmere, or silk with wool, to create a rich, tactile experience. Finally, accessories like scarves and belts can be the finishing touch that ties your layered look together.",
  },
];

export const trendingProducts = products.filter(p => p.tags?.includes('best-seller')).slice(0, 4);
