http:
  routers:
    apex-api:
      rule: "Host(`api.60sec.shop`)"
      service: apex-api
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    apex-admin:
      rule: "Host(`admin.60sec.shop`)"
      service: apex-admin
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    apex-storefront:
      rule: "HostRegexp(`{subdomain:.+}.60sec.shop`) || Host(`60sec.shop`)"
      service: apex-storefront
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    apex-api:
      loadBalancer:
        servers:
          - url: "http://api:3000"
    apex-admin:
      loadBalancer:
        servers:
          - url: "http://merchant-admin:3001"
    apex-storefront:
      loadBalancer:
        servers:
          - url: "http://storefront:3002"
