http:
  routers:
    apex-super-admin-dev:
      rule: "Host(`super-admin.60sec.shop`)"
      entryPoints:
        - websecure
      service: apex-super-admin-dev
      tls:
        certResolver: letsencrypt
      priority: 20000

    apex-merchant-admin-dev:
      rule: "Host(`admin.60sec.shop`)"
      entryPoints:
        - websecure
      service: apex-merchant-admin-dev
      tls:
        certResolver: letsencrypt
      priority: 20000

    apex-storage-admin-dev:
      rule: "Host(`storage-admin.60sec.shop`)"
      entryPoints:
        - websecure
      service: apex-super-admin-dev
      tls:
        certResolver: letsencrypt
      priority: 20000

    apex-api-dev:
      rule: "Host(`api.60sec.shop`)"
      entryPoints:
        - websecure
      service: apex-api-dev
      tls:
        certResolver: letsencrypt
      priority: 20000

    apex-storefront-dev:
      rule: "HostRegexp(`{host:.+}.60sec.shop`) || Host(`60sec.shop`)"
      entryPoints:
        - websecure
      service: apex-storefront-dev
      tls:
        certResolver: letsencrypt
      priority: 20000

  services:
    apex-api-dev:
      loadBalancer:
        servers:
          - url: "http://172.19.0.15:3000"
    apex-super-admin-dev:
      loadBalancer:
        servers:
          - url: "http://172.19.0.14:3001"
    apex-merchant-admin-dev:
      loadBalancer:
        servers:
          - url: "http://172.19.0.12:3001"
    apex-storefront-dev:
      loadBalancer:
        servers:
          - url: "http://172.19.0.13:3002"
